### ISSUE TITLE
v1.3 hardware is out but schematics are missing here.

### ISSUE THREAD

**Issue by lf-** [dc42/OrmerodSensorBoard#2]
[Spool3D](https://spool3d.ca/mini-differential-ir-height-sensing-board/) says that they have "v1.3" boards, but I only see v1.2 here if the commit history is to be believed.

Also, the link to the schematic PNG in [this blog post](https://miscsolutions.wordpress.com/mini-height-sensor-board/) is broken.

**Comment by dc42** [comment]
The schematic for version 1.3 is the same as for version 1.2. Only the PCB layout is different.

**Comment by amrithmmh** [comment]
can you share the schematics? the link seems broken

**Comment by amrithmmh** [comment]
thanks for making the circuit
Is this possible to use it with glass (stuck with 3M blue tape on top) ?

**Comment by lf-** [comment]
Consider reading the blog post detailing the project [here](
https://miscsolutions.wordpress.com/mini-height-sensor-board/) which states
supported surface types.

**Comment by amrithmmh** [comment]
so anything with nonreflective surface should work fine (for me blue tape on glass, which makes it non reflective)

**Comment by Deneteus** [comment]
Why were changes needed for the PCB layout between 1.2 and 1.3 if the schematic was the same?

**Comment by dc42** [comment]
To make manufacturing easier.

**Comment by Deneteus** [comment]
Is there any reason it cannot be made smaller? Say doing the same design but with edge mounted SMD sensors?

**Comment by dc42** [comment]
The width could be slightly smaller, it is limited by the spacing needed between the phototransistor and the outer IR diode. The height could be reduced by using a attiny44a MCU in a flat pack package instead of attiny25 and smaller connectors and programming pads, or perhaps a single 6-way connector for both. We intended to switch to a JST 1.5mm connector but we had push back from one of our OEM customers.
