### ISSUE TITLE
Eagle Files?

### ISSUE THREAD

**Issue by timmit99** [dc42/OrmerodSensorBoard#3]
Is there a possibility of getting the Eagle design files for this board? I'm looking to make some parts that use it and the Eagle .brd and .sch would be very useful.

**Comment by dc42** [comment]
Hi Tim,

Which variant of the board are you referring to?

Cheers

David Crocker, Escher Technologies Ltd.
http://www.eschertech.com
Tel. +44 (0)20 8144 3265 or +44 (0)7977 211486

**Comment by timmit99** [comment]
I'm looking for the eagle files for the V1.2? i think which has the SMD components.

**Comment by tchleb** [comment]
Can you please add the eagle files for the Mini-differential-IR V1.2.

**Comment by 3dle** [comment]
Can you please add the eagle files for the Mini-differential-IR V1.2.

**Comment by deHarro** [comment]
Hi David, @dc42,
I recently created a version of your board for TH IR components I had on hands already.

![grafik](https://user-images.githubusercontent.com/26298406/112107046-c031ed80-8bae-11eb-95e9-03a32deb559b.png)

The comrades asked for the Eagle files - I would be glad to share mine.
Is this ok for you?

Harry

**Comment by dc42** [comment]
Yes, that's OK.

**Comment by deHarro** [comment]
Ok, let's hope, they come back here... ;-)
Fine idea, by the way. I hope, my IR parts fit into the design.

Just curious... why don't you put your files into the repository?

Harry

**Comment by deHarro** [comment]
Here are my files, EAGLE V7.7

[MiniLedSensor_Harry.zip](https://github.com/dc42/OrmerodSensorBoard/files/6189988/MiniLedSensor_Harry.zip)

The IR parts are not of the correct types I have on hands, but the pads are ok.
The EAGLE design settings (especially the clearance for GND plane) are so that I can "etch" the board with my CNC router.

Harry

[edit]
sorry, made a mistake in the schematic (used resistor symbol as capacitor). Is fixed now.
